apiVersion: apps/v1
kind: Deployment
metadata:
  name: dronovdotnet
  labels:
    app: dronovdotnet
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dronovdotnet
  template:
    metadata:
      labels:
        app: dronovdotnet
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: dronovdotnet
          image: ghcr.io/dronov/dronovdotnet:v0.0.2
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: dronovdotnet-service
  labels:
    app: dronovdotnet
spec:
  selector:
    app: dronovdotnet
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
