server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = /2024/02/21/terraform-the-terrible-ru.html {
    return 301 /2024/02/21/terraform-the-terrible.html;
  }

  location = /2024/02/22/terraform-the-terrible-en.html {
    return 301 /2024/02/21/terraform-the-terrible.html;
  }

  location / {
    try_files $uri $uri/ =404;
  }
}
